version: '3.8'

name: CampaignView
services:
  db:
    image: "mysql"
    container_name: DB
    ports:
      - "3307:3306"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "mysql", "-uroot", "-ppassword", "campaignview" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  server:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "-h", "http://localhost:3000" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      server:
        condition: service_healthy
